### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by stefanct**
Hi,
while I was trying to get the debug bridge to run on newer systems (especially with a newer toolchain, it works with GDB 7.12+ now) I fixed some things on they way.
The last two patches probably need some more work and/or some vetting before merging them as I did not fully grasp the communication with the debug module and could only test on the Zedboard hardware. The rest should be pretty clear and uncontested I think (but ofc I am biased ;)

### CODE REVIEW

**Comment by haugoug** [comment]
Thanks a lot for your contribution !

**Comment by stefanct** [comment]
Hm, well... thanks, but I think that might have been a bit premature. Did you look at the reset/kill patches?

**Comment by stefanct** [comment]
@haugoug Also, unfortunately I made a mistake, see e53c194 for the fix.

**Comment by haugoug** [comment]
Ok great, can you create a pull request ?

**Pull request merged**
